### ISSUE TITLE
I can't use FNM on macOS (Failure hd)

### ISSUE THREAD

**Issue by gquittet** [Schniz/fnm#211]
Everytime I want to install a new version, the process runs during a lot of time. I need to kill it and try again in a new shell and I've this issue.

![image](https://user-images.githubusercontent.com/11082739/78545028-61d3f980-77fb-11ea-8923-9e41172defca.png)

The problem is that I can't use the version 12 after that.

I've tried with this line and without it in my shell settings:

![image](https://user-images.githubusercontent.com/11082739/78545265-d018bc00-77fb-11ea-9574-4439763588e3.png)

I've installed it with `brew install Schniz/tap/fnm`.

So at the moment, I'm staying with NVM and `fast-nvm-fish`

**Comment by gquittet** [comment]
![image](https://user-images.githubusercontent.com/11082739/78547165-ee33eb80-77fe-11ea-93b5-e6981116fe1c.png)

**Comment by rifler** [comment]
ubuntu trusty too

```
Version v8.17.0 was successfully downloaded
fnm: internal error, uncaught exception:
     (Failure hd)
```

**Comment by Schniz** [comment]
@gquittet I think the problem you're facing _after the failed installation_ is #178. I wonder why unzipping it doesn't work though!

@rifler I'm not sure what's the case here. We're using `tar` for `xz` files. is `tar` with `xz-utils` installed on ubuntu trusty?

**Comment by gquittet** [comment]
I'm on macOS and I can untar xz archives.

Rarely FNM works but most of the time I've got random errors.

![image](https://user-images.githubusercontent.com/11082739/78551372-e461b680-7805-11ea-973d-896111809eb5.png)

As you can see on the above screenshot I've stopped the installation after 42 seconds because I think something went wrong.

With this try, `install` isn't working but `use` yes, so I don't understand what's going on.

I can help you because I'm a JS/TS software developer but I have to learn ReasonML.

**Comment by Schniz** [comment]
> I'm on macOS and I can untar xz archives.

I know, this is why I suggested #178 as your issue. I suggested there:

> install everything inside a temp directory. If it crashes, the temp directory will be cleaned. If it won't crash, we can do mv THE_TEMP_DIR THE_DISTINATION

It still does not explain why it breaks or just takes a long time on your machine. What version of MacOS are you using?

**Comment by gquittet** [comment]
![image](https://user-images.githubusercontent.com/11082739/78552727-4f13f180-7808-11ea-8e37-84d0a52dc645.png)

**Comment by rifler** [comment]
> @rifler I'm not sure what's the case here. We're using tar for xz files. is tar with xz-utils installed on ubuntu trusty?

I have tar and xz (it is CI server):

```bash
> tar --version
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.

> dpkg -l xz-utils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-=====================================
ii  xz-utils         5.1.1alpha+20 amd64         XZ-format compression utilities
```

I noticed, that problem occurs with 8.x node
I've tried with 12 one time and with 8 several times - 12 ok and 8 times all failed

**Comment by gquittet** [comment]
I've also ArchLinux on my ThinkPad, I'll try on that OS after my work day.

**Comment by gquittet** [comment]
Same issue on ArchLinux but I haven't the (Failure hd) error on this OS.

![2020-04-06-190353](https://user-images.githubusercontent.com/11082739/78585039-746d2380-7839-11ea-91f5-c85e71cad7f4.png)

**Comment by gquittet** [comment]
My OS version:

![2020-04-06-190529](https://user-images.githubusercontent.com/11082739/78585119-9a92c380-7839-11ea-8367-b5912c26f0b4.png)

**Comment by gquittet** [comment]
![2020-04-06-190819](https://user-images.githubusercontent.com/11082739/78585360-0117e180-783a-11ea-9aff-d0c9b398755c.png)

**Comment by gquittet** [comment]
I like your tool and I want to help you to make it works!

**Comment by gquittet** [comment]
On ArchLinux I've fixed my issue on removing all the `fnm-shell-*` from /tmp. I'm trying the same fix on macOS.

**Comment by gquittet** [comment]
Fixed also on macOS.

1. Remove fnm with homebrew
2. Remove fnm folder and create another one. (for me it was `~/.local/share/fnm` but for most people it will be `~/.fnm`)
3. Remove all `fnm-shell-*` from /var/folders :

```bash
sudo find /var/folders -name "fnm-shell-*" > fnm-result.txt
for i in (cat fnm-result.txt); rm $i; end
rm fnm-result.txt
```
4. Install fnm with curl
```bash
curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --install-dir $HOME/.local/bin --skip-shell --force-install
```
5. Restart my shell (close it and open it again)
6. Install, use and alias are working great !

Sorry for the inconvenance but I wanted to make it work on my machine.

**Comment by gquittet** [comment]
Wait @rifler and @Schniz advices before closing the issue.

**Comment by Schniz** [comment]
Let's break it down:

* **once the installation is incomplete** fnm is in a bad state. This is well-known already and need to be taken care of (#178)

* I still don't understand why installations are taking so long on your machines. Do they ever finish before you do interrupt them with Ctrl-C? I mean, take a look at my screenshot which shows _13 seconds_ of installation time: ![13 second wall time clock 🕜  ](https://user-images.githubusercontent.com/2054772/78713260-aa3a0700-7922-11ea-8914-89857ab70b30.png)

**Comment by Schniz** [comment]
Closing for inactivity. feel free to reopen and explain further 😄
